name: GitHub CI
on: [push]

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux32_build:
    name: Linux x86 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: |
        docker run -v $GITHUB_WORKSPACE:/root/workdir -e TRAVIS_BRANCH=action -e TRAVIS_TAG=action multiarch/alpine:x86-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: stairspeedtest_reborn_linux32
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_linux32.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_linux32.tar.gz
        draft: true

  linux64_build:
    name: Linux x86_64 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: |
        docker run -v $GITHUB_WORKSPACE:/root/workdir -e TRAVIS_BRANCH=action -e TRAVIS_TAG=action multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: stairspeedtest_reborn_linux64
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_linux64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_linux64.tar.gz
        draft: true

  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i -e 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: |
        bash scripts/build.macos.release.sh
        bash scripts/build.macos.clients.sh
        mv base stairspeedtest
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: stairspeedtest_reborn_darwin64
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_darwin64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_darwin64.tar.gz
        draft: true
        
  windows64_build:
    name: Windows x86_64 Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel libtool autogen automake autoconf git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-libevent mingw-w64-x86_64-pcre2 mingw-w64-x86_64-freetype mingw-w64-x86_64-libpng mingw-w64-x86_64-bzip2 mingw-w64-x86_64-openssl mingw-w64-x86_64-libsodium mingw-w64-x86_64-c-ares mingw-w64-x86_64-boost mingw-w64-x86_64-libmariadbclient unzip p7zip
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Cache built dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-maindeps-64
      with:
        path: ~/maindeps
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/FETCH_HEAD') }} # key from git repos
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache built clients
      uses: actions/cache@v2
      env:
        cache-name: cache-clients-64
      with:
        path: ~/clients
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/FETCH_HEAD') }} # key from git repos
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Build dependencies and clients
      run: |
        bash scripts/build.windows.maindeps.sh
        bash scripts/build.windows.clients.sh
    - name: Build main program
      run: |
        bash scripts/build.windows.release.sh
        mv $USERPROFILE/clients/built/websocketd.exe base/tools/gui/
        mv $USERPROFILE/clients/built base/tools/clients
        mv base stairspeedtest
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: stairspeedtest_reborn_win64
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_win64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_win64.tar.gz
        draft: true

  windows32_build:
    name: Windows x86 Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel libtool autogen automake autoconf git mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-libevent mingw-w64-i686-pcre2 mingw-w64-i686-freetype mingw-w64-i686-libpng mingw-w64-i686-bzip2 mingw-w64-i686-openssl mingw-w64-i686-libsodium mingw-w64-i686-c-ares mingw-w64-i686-boost mingw-w64-i686-libmariadbclient unzip p7zip
        msystem: MINGW32
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Cache built dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-maindeps-32
      with:
        path: ~/maindeps
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/FETCH_HEAD') }} # key from git repos
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache built clients
      uses: actions/cache@v2
      env:
        cache-name: cache-clients-32
      with:
        path: ~/clients
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/FETCH_HEAD') }} # key from git repos
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Build dependencies and clients
      run: |
        bash scripts/build.windows.maindeps.sh
        bash scripts/build.windows.clients.sh
    - name: Build main program
      run: |
        bash scripts/build.windows.release.sh
        mv $USERPROFILE/clients/built/websocketd.exe base/tools/gui/
        mv $USERPROFILE/clients/built base/tools/clients
        mv base stairspeedtest
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: stairspeedtest_reborn_win32
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_win32.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_win32.tar.gz
        draft: true
